### ISSUE TITLE
转码时如果下载失败就挂掉

### ISSUE THREAD

**Issue by hdcola** [HDCodePractice/MusicPlayer#20]
csbot      | [ffmpeg] Correcting container in "downloads/qX2GsMj7154.m4a"
csbot      | [Errno 2] No such file or directory: '/data/downloads/xBlJz-HvyAU.raw'
csbot      | Traceback (most recent call last):
csbot      |   File "/usr/local/lib/python3.9/site-packages/pyrogram/dispatcher.py", line 217, in handler_worker
csbot      |     await handler.callback(self.client, *args)
csbot      |   File "/MusicPlayer/plugins/player.py", line 382, in skip_track
csbot      |     await mp.skip_current_playing()
csbot      |   File "/MusicPlayer/utils.py", line 117, in skip_current_playing
csbot      |     os.remove(os.path.join(
csbot      | FileNotFoundError: [Errno 2] No such file or directory: '/data/downloads/xBlJz-HvyAU.raw'

**Comment by hdcola** [comment]
csbot      | [youtube] xBlJz-HvyAU: Downloading webpage
csbot      | - START PLAYING: Jason Mraz - I'm Yours (Official Video)
csbot      | [youtube] xBlJz-HvyAU: Downloading webpage
csbot      | ERROR: unable to download video data: HTTP Error 403: Forbidden
csbot      | downloads/xBlJz-HvyAU.m4a: No such file or directory
csbot      | Task exception was never retrieved
csbot      | future: <Task finished name='Task-25270' coro=<playout_ended_handler() done, defined at /MusicPlayer/utils.py:284> exception=Error('ffmpeg error (see stderr output for detail)')>
csbot      | Traceback (most recent call last):
csbot      |   File "/MusicPlayer/utils.py", line 289, in playout_ended_handler
csbot      |     await mp.skip_current_playing()
csbot      |   File "/MusicPlayer/utils.py", line 123, in skip_current_playing
csbot      |     await self.download_audio(playlist[1])
csbot      |   File "/MusicPlayer/utils.py", line 174, in download_audio
csbot      |     ffmpeg.input(original_file).output(
csbot      |   File "/usr/local/lib/python3.9/site-packages/ffmpeg/_run.py", line 325, in run
csbot      |     raise Error('ffmpeg', out, err)
csbot      | ffmpeg._run.Error: ffmpeg error (see stderr output for detail)

**Comment by hdcola** [comment]
不再进行转码，所以这个可以close
