### ISSUE TITLE
如果没有下载完，playlist播放失败

### ISSUE THREAD

**Issue by hdcola** [HDCodePractice/MusicPlayer#9]
- START PLAYING: 梁靜茹-兒歌(KTV)
[Errno 2] No such file or directory: './downloads/RP2TQUyRCVI.raw'
Traceback (most recent call last):
  File "/home/pi/py3/lib/python3.9/site-packages/pyrogram/dispatcher.py", line 217, in handler_worker
    await handler.callback(self.client, *args)
  File "/home/pi/MusicPlayer/plugins/player.py", line 382, in skip_track
    await mp.skip_current_playing()
  File "/home/pi/MusicPlayer/utils.py", line 116, in skip_current_playing
    os.remove(os.path.join(
FileNotFoundError: [Errno 2] No such file or directory: './downloads/RP2TQUyRCVI.raw'

**Comment by hdcola** [comment]
没有下载完的播放策略要想想，也许直接跳过更好一些
